version: 2

sources:
  - name: raw
    database: bases-sql-485411
    schema: gz_raw_data
    loader: bigquery
    tables:
      - name: sales #alias
        identifier: raw_gz_sales
        description: Vente de gz
        columns:
          - name: orders_id
            description: id des ventes dans sales
        tests:
               - unique:
                  column_name: "(orders_id || '-' || pdt_id)"
               - not_null:
                  column_name: "(orders_id || '-' || pdt_id)"
             
      - name: product #alias
        identifier: raw_gz_product
        description: produit de gz
        columns:
          - name : products_id
            description: id des produits dans products
            tests:
              - unique
              - not_null
      - name: ship #alias
        identifier: raw_gz_ship
        description: cout de transport de gz
        columns:
          - name : orders_id
            description: id des produits dans products
            tests:
              - unique
              - not_null